import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavBar from './NavBar';
import QueryClientProvider from "./QueryClientProvider";
import AuthProvider from './auth/Provider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <QueryClientProvider>
        <AuthProvider>
          <Theme>
            <NavBar />
            <main className='p-5'>{children}</main>
          </Theme>
        </AuthProvider>
      </QueryClientProvider>
      </body>
    </html>
  )
}
